//project name : IR_cam_PIC24f
#ifndef PROJECT_SPECIFIC_H
#define PROJECT_SPECIFIC_H

#include <xc.h>
#define PIC_TYPE_DEFINITIONS
#define CLOCK_DEFINITIONS
#define UART_DEFINITIONS
#define I2C_DEFINITIONS
#define PIN_DEFINITIONS
#define LCD_DEFINITIONS
#define SOFTWARE_PARAMETERS

#ifdef PIC_TYPE_DEFINITIONS
/* PIC TYPE DEFINITIONS*/
//#define PIC24F16KA102
#define PIC24FJ128GA306
//#define PIC24FJ64GA004
#endif
#ifdef CLOCK_DEFINITIONS
/*CLOCK PARAMETERS*/

#define CLK_FRC_WITH_PLL_32MHZ_without_ClockSwitching

#endif
#ifdef UART_DEFINITIONS
/* UART DEFINITIONS*/
    #define PIC24FJ128GA306_uart1
    #define PIC24FJ128GA306_uart2
    #define BRGH_VALUE_HIGH
    //#define BRGH_VALUE_LOW
    #define BAUDRATE1 115200
    #define BAUDRATE2 115200
    #define ONE_STOP_BIT
    //#define TWO_STOP_BIT
    //#define uart_for_debug
#endif
#ifdef SOFTWARE_PARAMETERS
/*Data Transfer Method*/
//#define PIC24FJ128GA306_16bit_SSD1289
#define PIC24FJ128GA306_Serial_4pin_ST7789
#define command_data_via_SPI
#endif
#ifdef I2C_DEFINITIONS
/* I2C DEFINITIONS*/
//#define PIC24F16KA102_I2C1
//#define PIC24FJ128GA306_I2C1
//#define PIC24FJ128GA306_I2C2
//#define I2C2_MODULE
#define PIC24F_I2C1_MODULE
//#define DEFAULT_BUS_SPEED 400 
#endif
#ifdef PIN_DEFINITIONS
/*PIN DEFINITIONS FOR PIC24FJ128GA306*/
/*ICSP PINS*/
//pin15 --> PGEC1/CVREF-/AN1/RP1/SEG6/CTED12/CN3/RB1<------------------THIS ONE IS GONING TO BE USED FOR ICSP
//pin16 --> PGED1/CVREF+/AN0/RP0/SEG7/PMA6/CN2/RB0<-------------------------THIS ONE IS GONING TO BE USED FOR ICSP
//pin17 --> PGEC2/AN6/RP6/LCDBIAS3/CN24/RB6
//pin18 --> PGED2 / AN7/RP7/CN25/RB7
//pin11 --> PGEC3 / AN5/ C1INA/ RP18 /SEG2/ CN7/RB5
//pin12 --> PGED3 / AN4/ C1INB/ RP28 / SEG3/CN6/RB4
/*UART PINS*/
//U1TX----->PIN21 (AN8/RP8/SEG31/COM7/CN26/RB8)     <------------------THIS ONE IS GONING TO BE USED FOR U1TX
//U1RX----->PIN22 (AN9/RP9/SEG30/COM6/PMA7/CN27/RB9)<------------------THIS ONE IS GONING TO BE USED FOR U1RX
//U2TX----->PIN29 (AN14/RP14/..../RB14)<-------------------------------THIS ONE IS GONING TO BE USED FOR U2TX
//U2TX----->PIN30 (AN15/RP29/..../RB15)<-------------------------------THIS ONE IS GONING TO BE USED FOR U2RX
/*I2C PINS*/
/*  
 SCL1-->PIN37<------------------THIS ONE IS GONING TO BE USED FOR SCL
 SDA1-->PIN36<------------------THIS ONE IS GONING TO BE USED FOR SDA
 SCL2-->PIN32
 SDA2-->PIN31
 */
/*SPI PINS*/
//SDI1-->PIN33<------------------THIS ONE IS GOING TO BE CONFIGURED FOR SDI
//SCK1-->PIN34<------------------THIS ONE IS GOING TO BE CONFIGURED/USED FOR SCK(SCL at LCD SCREEN)
//SDO1-->PIN42<------------------THIS ONE IS GOING TO BE CONFIGURED/USED FOR SDO(SDA at LCD SCREEN)
/*GEN_PURPOSE IO PINS*/
//OUTPUT_PIN35-->PIN35
//OUTPUT_PIN44-->PIN44
//INPUT_PIN43--->PIN43
//RST----------->PIN30<----------THIS ONE IS GOING TO BE USED FOR LCD SCREEN
//DC------------>PIN29<----------THIS ONE IS GOING TO BE USED FOR LCD SCREEN
#endif
#ifdef LCD_DEFINITIONS
/*LCD DEFINITIONS*/
//#define LCD
#endif

#endif
